name: publish-github-package

on: [ push ]

jobs:
  build-and-publish:
    runs-on: macos-latest

      #    steps:
      #      - name: Checkout repository
      #        uses: actions/checkout@v3
      #        with:
      #          token: ${{ secrets.ZIGGEO_PAT }}
      #          submodules: true
      #
      #      - name: Retrieve Version
      #        run: |
      #          echo "::set-output name=VERSION_NAME::$(gradle -q printVersionName)"
      #        id: android_version


      #      - name: Set up Java 11
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: '11'

      #      - name: Build with Gradle
      #        run: gradle sdk:assemble

      #      - name: Get version
      #        run: |
      #          echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      #
      #      - name: Publish with Gradle
      #        run: gradle publish


      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: '11'
        - name: Build APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: apk
            path: app/build/outputs/apk/debug/app-debug.apk